M48
; DRILL file {KiCad (7.0.0)} date Mon Jul 17 21:55:51 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-07-17T21:55:51-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1358
%
G90
G05
T1
X1.8163Y-2.6823
X1.8163Y-3.5575
X2.7545Y-2.6823
X2.7545Y-3.5575
T0
M30
